services:
    frankenphp:
        container_name: "${APP_NAME}"
        restart: always
        deploy:
            resources:
                limits:
                    cpus: '0.8'
                    memory: 512M
        build:
            context: ./docker/frankenPHP
            dockerfile: Dockerfile
        image: api/frankenphp
        entrypoint: php artisan octane:frankenphp --workers=${WORKERS} --max-requests=250 --port=8000
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        networks:
            - net

    pgsql:
        container_name: "pgsql"
        image: 'postgres:17'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'pgsql:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - net

    php:
        container_name: "php"
        build:
            context: ./docker/PHP/8_3
            dockerfile: Dockerfile
        image: api/php
        volumes:
            - '.:/var/www/html'
        networks:
            - net
networks:
    net:
        driver: bridge
        name: net
volumes:
    pgsql:
        driver: local
